### ISSUE TITLE
Stash 覆写中引用外部资源更新间隔问题

### ISSUE THREAD

**Issue by wydinhk** [Coldvvater/Mononoke#1]
您创建的覆写中引用的 js 脚本（或外部策略组），interval 均设为 3600，但我追踪发现这些脚本中许多已超过几个月没有更新，若每小时将他们强制后台更新一次，或许会增加不必要的资源占用及耗电。

因此建议考虑更改为 interval 为 86400 或更长。若用户认为脚本需要立即更新，自行点击“远程资源”操作即可。谢谢！

**Comment by Coldvvater** [comment]
> 您创建的覆写中引用的 js 脚本（或外部策略组），interval 均设为 3600，但我追踪发现这些脚本中许多已超过几个月没有更新，若每小时将他们强制后台更新一次，或许会增加不必要的资源占用及耗电。
> 
> 因此建议考虑更改为 interval 为 86400 或更长。若用户认为脚本需要立即更新，自行点击“远程资源”操作即可。谢谢！

感谢反馈，后期会修改。
