### ISSUE TITLE
Clash Meta for Android 导入 yaml 文件、建立连接一段时间后 FCM 服务连接超时/失败

### ISSUE THREAD

**Issue by HiRA017** [Coldvvater/Mononoke#14]
查询 FCM Diagnostics 状态为 
```
Server: Connecting/Not connected
Host: alt3-mtalk.google.com
Port: 443
Time disconnected: 5:11:38
Last close code: ERR_HEARTBEAT_ACK_TIMEOUT
```

事件日志中

> net=1: Close err:6 time:18102
> **net=1: Connecting using McsConnection{NetworkWrapper{100}, type=1, wasVpnBypassed=ture}
> net=1: Failed connection err:24**

之后则是加粗部分不断出现，直至关闭Clash Meta。

（参考：附件为基于 Evovle.yaml 个性化的自用文件，是否是我有哪里写错了呢）
[1697704817956.-.pdf](https://github.com/Coldvvater/Mononoke/files/13109624/1697704817956.-.pdf)

**Comment by Coldvvater** [comment]
尝试添加Host，mtalk.google.com = 108.177.125.188

**Comment by HiRA017** [comment]
谢谢！大部分都解决了，以防万一我也添加了 alt1～8 域名的 host。只有小部分 app 仍然需要关闭 Clash 才能成功收到堆积的推送通知。（因为人在境外，需求仅为部分服务如版权限制的内容才需要内地代理，大部分服务都是走直连 DIRECT 规则，但是不知道为什么 FCM 不按规则走…）

直接在配置文件里的转发规则 rule 区域写` - DOMAIN,mtalk.google.com,DIRECT `是否可以一劳永逸地让 FCM 走
直连呢？

**Comment by Coldvvater** [comment]
可以添加GoogleFCM分流，不用一条条写
