### ISSUE TITLE
关于使用stash规则的反馈

### ISSUE THREAD

**Issue by GD2021** [Coldvvater/Mononoke#17]
问题1：openai分流被劫持
排查原因：策略组中【Global】在【openai】的前面，如果【Global】设置为HK，【OpenAI】设置为US,会出现OpenAI走HK,
解决：一是把【Global】与【OpenAI】改为相同节点，或者把【Global】策略组后移。第一种方法有种弊端，那就是其他网站不走HK速度慢。

![image](https://github.com/Coldvvater/Mononoke/assets/81171294/2316cdc5-9cf5-4855-92e2-46380b362b51)
![image](https://github.com/Coldvvater/Mononoke/assets/81171294/63bf5789-b401-4f31-a3e8-2aebdf744590)

客户端: Stash for TVos 做旁路网关

**Comment by Coldvvater** [comment]
那是因为classical text规则问题，已改回yaml

**Comment by GD2021** [comment]
）)已测试，正常。
太棒了！！终于可以流畅的玩耍了。

推荐几个规则，至于添加与否，请您甄别

### 直连
- [全球直连](https://raw.githubusercontent.com/mphin/ACL4SSR/main/rules/GlobalDirect.list)

### 相对精简的AD规则
- [毒奶去广告计划](https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/QuantumultX/rule/Adblock4limbo.list)
- [Adguard_Rules.list](https://raw.githubusercontent.com/QXPublic/MyUtilize/main/FlowRule/Adguard_Rules.list)
- [raw.githubusercontent.com/RuCu6/QuanX/main/Rules/MyBlockAds.list](https://raw.githubusercontent.com/RuCu6/QuanX/main/Rules/MyBlockAds.list)

### AI
- [微软Copilot.list](https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Loon/Rule/Copilot.list)

### TV观影类
- [XPTV](https://mirror.ghproxy.com/https://raw.githubusercontent.com/fangkuia/XPTV/main/X/XPTV1%EF%BC%88%E5%9B%BD%E5%86%85%EF%BC%89.list)
- [CMSPlayer.list](https://raw.githubusercontent.com/byhooi/Surge/main/Rule/CMSPlayer.list)
- [Porn.list](https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Porn.list)
- [Emby媒体库](https://raw.githubusercontent.com/Repcz/Tool/X/Stash/Rules/Emby.list)
