### ISSUE TITLE
贴吧规则已经失效，app2smile大佬的脚本已经更新

### ISSUE THREAD

**Issue by yzxj3180** [Coldvvater/Mononoke#2]
host地址和其中一个http-response已经被更新，并且建议覆写中加入配套的dns屏蔽。

**Comment by yzxj3180** [comment]
您更新脚本后，stash测试下脚本失效，loon测试没问题

**Comment by Coldvvater** [comment]
> 您更新脚本后，stash测试下贴吧脚本失效，还是有广告，loon测试没问题

不好意思，现在才看到，已经更新了，你看看行不行，不行再反馈，谢谢。
