### ISSUE TITLE
弱弱地问一句，如何添加多个订阅链接?

### ISSUE THREAD

**Issue by ixbcqq** [Coldvvater/Mononoke#21]
如题，在Stash里面用这个配置文件，添加多个机场的链接会报错，那要怎样能添加呢？

**Comment by ixbcqq** [comment]
> > 如题，在Stash里面用这个配置文件，添加多个机场的链接会报错，那要怎样能添加呢？
> 
> sub-store ，具体操作看看油管相关视频教程

这个方式无法把配置文件同步到Apple TV的

**Comment by Coldvvater** [comment]
> 如题，在Stash里面用这个配置文件，添加多个机场的链接会报错，那要怎样能添加呢？

在UI添加
