### ISSUE TITLE
Games规则有漏

### ISSUE THREAD

**Issue by ixbcqq** [Coldvvater/Mononoke#23]
Games我已经选了走代理，但还是直连了，麻烦修复一下，谢谢啦。是手机版的PUBG，比较常见的游戏了
![IMG_9497](https://github.com/Coldvvater/Mononoke/assets/131175449/c65cfd12-c6b8-4e08-afc2-9275a3e05d29)

**Comment by Coldvvater** [comment]
> Games我已经选了走代理，但还是直连了，麻烦修复一下，谢谢啦。是手机版的PUBG，比较常见的游戏了 ![IMG_9497](https://private-user-images.githubusercontent.com/131175449/334264540-c65cfd12-c6b8-4e08-afc2-9275a3e05d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDUwNjAsIm5iZiI6MTcxNzMwNDc2MCwicGF0aCI6Ii8xMzExNzU0NDkvMzM0MjY0NTQwLWM2NWNmZDEyLWM2YjgtNGUwOC1hZmMyLTkyNzVhM2UwNWQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwNTA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGI2OWNiODA2YjQxY2U4M2JlMjcxMWJhYmNmNWE1MjAxN2EwNDFkYWU4NGYyMDRiYjE3NzlhYmJlZTk1YzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RIuIajc29eX_ErWKZoOTFvzF39iUY1akMtRHIyzzLuY)

是外区的pubg吗？

**Comment by ixbcqq** [comment]
> > Games我已经选了走代理，但还是直连了，麻烦修复一下，谢谢啦。是手机版的PUBG，比较常见的游戏了 ![IMG_9497](https://private-user-images.githubusercontent.com/131175449/334264540-c65cfd12-c6b8-4e08-afc2-9275a3e05d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDUwNjAsIm5iZiI6MTcxNzMwNDc2MCwicGF0aCI6Ii8xMzExNzU0NDkvMzM0MjY0NTQwLWM2NWNmZDEyLWM2YjgtNGUwOC1hZmMyLTkyNzVhM2UwNWQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwNTA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGI2OWNiODA2YjQxY2U4M2JlMjcxMWJhYmNmNWE1MjAxN2EwNDFkYWU4NGYyMDRiYjE3NzlhYmJlZTk1YzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RIuIajc29eX_ErWKZoOTFvzF39iUY1akMtRHIyzzLuY)
> 
> 是外区的pubg吗？

是的

**Comment by Coldvvater** [comment]
> > > Games我已经选了走代理，但还是直连了，麻烦修复一下，谢谢啦。是手机版的PUBG，比较常见的游戏了 ![IMG_9497](https://private-user-images.githubusercontent.com/131175449/334264540-c65cfd12-c6b8-4e08-afc2-9275a3e05d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDUwNjAsIm5iZiI6MTcxNzMwNDc2MCwicGF0aCI6Ii8xMzExNzU0NDkvMzM0MjY0NTQwLWM2NWNmZDEyLWM2YjgtNGUwOC1hZmMyLTkyNzVhM2UwNWQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwNTA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGI2OWNiODA2YjQxY2U4M2JlMjcxMWJhYmNmNWE1MjAxN2EwNDFkYWU4NGYyMDRiYjE3NzlhYmJlZTk1YzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RIuIajc29eX_ErWKZoOTFvzF39iUY1akMtRHIyzzLuY)
> > 
> > 
> > 是外区的pubg吗？
> 
> 是的

使用的game分流规则好像不包含这个游戏的域名，你可以自行添加

**Comment by ixbcqq** [comment]
> > > > Games我已经选了走代理，但还是直连了，麻烦修复一下，谢谢啦。是手机版的PUBG，比较常见的游戏了 ![IMG_9497](https://private-user-images.githubusercontent.com/131175449/334264540-c65cfd12-c6b8-4e08-afc2-9275a3e05d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDUwNjAsIm5iZiI6MTcxNzMwNDc2MCwicGF0aCI6Ii8xMzExNzU0NDkvMzM0MjY0NTQwLWM2NWNmZDEyLWM2YjgtNGUwOC1hZmMyLTkyNzVhM2UwNWQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwNTA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGI2OWNiODA2YjQxY2U4M2JlMjcxMWJhYmNmNWE1MjAxN2EwNDFkYWU4NGYyMDRiYjE3NzlhYmJlZTk1YzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RIuIajc29eX_ErWKZoOTFvzF39iUY1akMtRHIyzzLuY)
> > > 
> > > 
> > > 是外区的pubg吗？
> > 
> > 
> > 是的
> 
> 使用的game分流规则好像不包含这个游戏的域名，你可以自行添加

Ok
