### ISSUE TITLE
请教一下，使用这种描点配置文件时，能否对特定domain指定固定的节点？

### ISSUE THREAD

**Issue by Troray** [Coldvvater/Mononoke#25]
例如用clash客户端，配置如：
```
proxy-providers: 
  jichang: {<<: *p, path: ./proxy_providers/jichang.yaml, url: "https://www.机场订阅地址.com"}
  zijian: {<<: *p, path: ./proxy_providers/zijian.yaml, url: "https://www.多个自建整合订阅地址.com"}
```
此时，机场和自建都有 香港、韩国、日本 的多个节点。
假设自建的有 `🇭🇰 HK` `🇭🇰 HK2`  `🇯🇵 JP` `🇯🇵 JP2` 如图：
![Snipaste_2024-07-24_22-24-42](https://github.com/user-attachments/assets/de9a2f44-a530-43ff-b13a-0f2dc8b49f93)
![Snipaste_2024-07-24_22-25-27](https://github.com/user-attachments/assets/ac7207c8-7b81-4a84-ba73-9c4f0970fd60)

那么能通过配置文件写
```
- DOMAIN-SUFFIX,google.com,????/🇭🇰 HK2
- DOMAIN-SUFFIX,chatgpt.com,????/🇯🇵 JP2
```

如果是普通的proxies类型，我倒是知道直接写上节点名称就可以了。
但是描点配置类型，我不知道是否能指定固定节点。

**Comment by Coldvvater** [comment]
可以
