### ISSUE TITLE
规则有错误

### ISSUE THREAD

**Issue by Infatuation-Fei** [Coldvvater/Mononoke#3]
no-resolve是放到最后的，REJECT在前
![Uploading 2B6F915A-7416-4242-85B4-BC0DE2F7D464.jpeg…]()
至少看到了Stash覆写的贴吧和知乎都有这个错误

**Comment by Infatuation-Fei** [comment]
![987B2123-B2BE-479B-9D48-102AF092E7BC](https://user-images.githubusercontent.com/58471624/186823974-36400af7-95c4-472e-b204-9ec664119dfc.jpeg)
插了图没显示出来，补一下

**Comment by Infatuation-Fei** [comment]
![5B1F21D0-60D4-43E4-B977-DE28C748B80F](https://user-images.githubusercontent.com/58471624/186824211-34a80f5c-07f0-45bd-a65e-42fd83ed3e09.jpeg)

**Comment by Coldvvater** [comment]
> ![5B1F21D0-60D4-43E4-B977-DE28C748B80F](https://user-images.githubusercontent.com/58471624/186824211-34a80f5c-07f0-45bd-a65e-42fd83ed3e09.jpeg)

写大佬提醒，这就改
