### ISSUE TITLE
求支持emby调用第三方播放器的stash覆写

### ISSUE THREAD

**Issue by yao71232** [Coldvvater/Mononoke#4]
hostname = *.mb3admin.com, *.emby.wtf, *.plusmedia.site, *.jmsooo.com

# 播放解锁
^https?:\/\/mb3admin.com\/admin\/service\/registration\/validateDevice url script-response-body https://raw.githubusercontent.com/rartv/EmbyPublic/test/quantumult-x/unlock.js
# 解决QX抓取某些公益服该请求乱码问题
\/Users\/\w{32}\/Items\/\d+\? url request-header (\r\n)Accept-Encoding:.+ request-header $Accept-Encoding: gzip, deflate, br
# 添加外部播放器连接
\/Users\/\w{32}\/Items\/\d+\? url script-response-body https://raw.githubusercontent.com/rartv/EmbyPublic/test/surge/emby-plugin.js
# 打开外部播放器
\/plugin\/scheme url script-echo-response https://raw.githubusercontent.com/rartv/EmbyPublic/test/surge/emby-plugin.js
# 资源路径伪静态
(\/Videos\/\d+\/stream\/.+\?.+&filename)|(\/Videos\/\d+\/\w{32}\/Subtitles\/\d+\/.+\?.+&filename) url script-request-header https://raw.githubusercontent.com/rartv/EmbyPublic/test/surge/emby-plugin.js
# 下载文件重命名
(\/Videos\/\d+\/stream\/.+\?.+&filename)|(\/Videos\/\d+\/\w{32}\/Subtitles\/\d+\/.+\?.+&filename) url script-response-header https://raw.githubusercontent.com/rartv/EmbyPublic/test/quantumult-x/download-file-rename.js

**Comment by yao71232** [comment]
https://raw.githubusercontent.com/rartv/EmbyPublic/test/quantumult-x/emby-plugin.conf这是QX的，自己不知道怎么改

**Comment by Coldvvater** [comment]
> https://raw.githubusercontent.com/rartv/EmbyPublic/test/quantumult-x/emby-plugin.conf这是QX的，自己不知道怎么改

明天我看看
