### ISSUE TITLE
请教一下关于mitm的配置

### ISSUE THREAD

**Issue by shallbytwo** [Coldvvater/Mononoke#7]
感谢分享的配置文件，有个疑问想请教一下，
``
[mitm]
skip_validating_cert = true
``
请问这个``skip_validating_cert``设置为true是有什么用处呢？设置false又有啥影响吗？
谢谢！

**Comment by Coldvvater** [comment]
> 感谢分享的配置文件，有个疑问想请教一下， `[mitm] skip_validating_cert = true` 请问这个`skip_validating_cert`设置为true是有什么用处呢？设置false又有啥影响吗？ 谢谢！

这个是跳过证书验证，要想一些mitm生效一般设置true为好
